import '../globals.css';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/utils/next-auth';
import NotificationProvider from '@/provider/notification-provider';

import AdminLayout from '@/components/Admin/Layout/AdminLayout';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <NotificationProvider>
          <AdminLayout session={session}>{children}</AdminLayout>
        </NotificationProvider>
      </body>
    </html>
  );
}
