import './globals.css';
import { Inter } from 'next/font/google';
import Layout from '@/components/Layout';
import CartContextProvider from '@/provider/cart-provider';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartContextProvider>
          <Layout>{children}</Layout>
        </CartContextProvider>
      </body>
    </html>
  );
}
