import './globals.css';
import { Inter } from 'next/font/google';
import Layout from '@/components/Layout';
import CartContextProvider from '@/provider/cart-provider';
import { getServerSession } from "next-auth/next"
import { authOptions } from '@/utils/next-auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartContextProvider>
          <Layout session={session}>{children}</Layout>
        </CartContextProvider>
      </body>
    </html>
  );
}
